
jsj:
  username: John
  password: Password123
  url: www.example.com
  jms: 
    username: Gollum
    password: GollumPassword99
    url: www.dictionary.example.com


--- #File separator
spring:
  profiles: de
jsj:
    username: "John $$$ IN $$$ German"
   
--- 
spring:
  profiles: es
jsj:
    username: "de Jesus &&& IN &&& Spanish"  